### ISSUE TITLE
About claims that torch-v2 is SF

### ISSUE THREAD

**Issue by cj5716** [0wwafa/torch-v2#1]
It has been shown that torch V2 is not SF, as seen by different bench, UCI options etc.

Could it be that you were running the wrong executable when you were testing that? Could you recheck?

Can I confirm that this is the output?
![2024-08-09_13_32_31-C__WINDOWS_system32_cmd exe_-_torch-2 exe](https://github.com/user-attachments/assets/dfd6441e-f477-4475-a402-751e4f37c740)

This is the bench:
```Bench completed.
2914797 nodes 82701 nps
```

**Comment by cj5716** [comment]
BTW - you were mistakenly kicked from SF discord, feel free to rejoin and apologies for the inconvenience

**Comment by 0wwafa** [comment]
> It has been shown that torch V2 is not SF, as seen by different bench, UCI options etc.
> 
> Could it be that you were running the wrong executable when you were testing that? Could you recheck?
> 
> Can I confirm that this is the output? ![2024-08-09_13_32_31-C__WINDOWS_system32_cmd exe_-_torch-2 exe](https://private-user-images.githubusercontent.com/125858804/356583612-dfd6441e-f477-4475-a402-751e4f37c740.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMzM3ODcsIm5iZiI6MTcyMzIzMzQ4NywicGF0aCI6Ii8xMjU4NTg4MDQvMzU2NTgzNjEyLWRmZDY0NDFlLWY0NzctNDQ3NS1hNDAyLTc1MWU0ZjM3Yzc0MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQxOTU4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMGUwYjc4NmIwMTdmNjMyMGNkNTI0YjY4NmMyMGY2Mzg5MDQ2NTUzNDUxYTc5MmEyYzE5OTk2ZGRjYzQ5N2JiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eHM82aLu-aGDvHOwPZiy-Rnq8176sM4mLmGzGX-0VeY)
> 
> This is the bench:
> 
> ```
> 2914797 nodes 82701 nps
> ```

```
$ ./torch-2
Torch by A. Grant, F. Eggers, K. Kahre, M. Whiteley, J. Honnold from Chess.com
uci
id name Torch 2 WASM Multithreaded
id author A. Grant, F. Eggers, K. Kahre, M. Whiteley, J. Honnold from Chess.com
option name ClearHash type button
option name Contempt type spin default 0 min -128 max 128
option name ContemptOverrides type string default <empty>
option name EvalFile type string default <embedded>
option name Hash type spin default 16 min 2 max 1048576
option name Minimal type check default false
option name MoveOverhead type spin default 100 min 0 max 5000
option name MultiPV type spin default 1 min 1 max 256
option name Normalize type check default true
option name NormalizeFactor type spin default 242 min 0 max 1000
option name Ponder type check default false
option name SilenceUCI type check default false
option name Syzygy50MoveRule type check default false
option name SyzygyDTZFiltering type check default true
option name SyzygyPath type string default <empty>
option name SyzygyProbeDepth type spin default 1 min 1 max 127
option name SyzygyProbeLimit type spin default 7 min 1 max 7
option name Threads type spin default 1 min 1 max 256
option name UCI_Chess960 type check default false
option name UCI_Opponent type string default <empty>
info string licensed to chess.com
uciok
```

**Comment by 0wwafa** [comment]
> It has been shown that torch V2 is not SF, as seen by different bench, UCI options etc.

I didn't say it **is SF**, I meant **it looks like some modification of SF**

**Comment by cj5716** [comment]
Yes, but I (and several others) have verified that it is not a modification of SF

**Comment by cj5716** [comment]
Resolved on discord. Conclusion: misunderstanding, not a modification of SF
